@startuml sequenza
PeerReviewServer -> PeerReviewStrategy: configure_train(                                                \
    rnd: int, parameters: Parameters, client_manager: ClientManager                                         \
)
PeerReviewStrategy -> PeerReviewServer: client_instructions: List[Tuple[ClientProxy, FitIns]]
PeerReviewServer -> PeerReviewStrategy: aggregate_train(                                                \
    rnd: int, results: List[Tuple[ClientProxy, FitRes]], failures: List[BaseException]                      \
)
PeerReviewStrategy -> PeerReviewServer:                                                                 \
    aggregate_result: List[Tuple[Optional[Parameters], Dict[str, Scalar]]]
loop do while stop_flag != TRUE
    PeerReviewServer -> PeerReviewStrategy: configure_review(                                           \
        rnd: int, parameters: Parameters, client_manager: ClientManager,                                    \
        parameters_aggregated: List[Optional[Parameters]], metrics_aggregated: List[Dict[str, Scalar]]      \
    )
    PeerReviewStrategy -> PeerReviewServer: review_instructions: List[Tuple[ClientProxy, FitIns]]
    PeerReviewServer -> PeerReviewStrategy: aggregate_review(                                           \
        rnd: int, results: List[Tuple[ClientProxy, FitRes]], failures: List[BaseException]                  \
    )
    PeerReviewStrategy -> PeerReviewServer:                                                             \
        aggregate_result: List[Tuple[Optional[Parameters], Dict[str, Scalar]]]
    PeerReviewServer -> PeerReviewStrategy: stop_review(                                                \
        rnd: int,parameters: Parameters, client_manager: ClientManager,                                     \
        parameters_aggregated: List[Optional[Parameters]], metrics_aggregated: List[Dict[str, Scalar]]      \
    )
    PeerReviewStrategy -> PeerReviewServer: stop_flag: bool
end
PeerReviewServer -> PeerReviewStrategy: aggregate_after_review(                                         \
    rnd: int,                                                                                               \
    review_results: List[Tuple[Optional[Parameters], Dict[str, Scalar]]],                                   \
    parameters: Optional[Parameters]                                                                        \
)
PeerReviewStrategy -> PeerReviewServer: parameters_aggregated: Optional[Parameters]:
@enduml