@startuml sequenza
PeerReviewServer -> PeerReviewStrategy: configure_train()
PeerReviewStrategy -> ClientManager: sample()
ClientManager -> PeerReviewStrategy: clients
PeerReviewStrategy -> PeerReviewServer: client_instructions
PeerReviewServer -> PeerReviewClient: fit_client(client_instructions, REVIEW=False|None)
PeerReviewClient -> PeerReviewServer: FitRes(REVIEW=False)
PeerReviewServer -> PeerReviewStrategy: aggregated_result()
PeerReviewStrategy -> PeerReviewServer: aggregated_result
loop do while stop_flag != TRUE
    PeerReviewServer -> PeerReviewStrategy: configure_review(aggregated_result)
    PeerReviewStrategy -> ClientManager: sample()
    ClientManager -> PeerReviewStrategy: clients
    PeerReviewStrategy -> PeerReviewServer: review_instructions
    PeerReviewServer -> PeerReviewClient: fit_client(review_instructions, REVIEW=True)
    PeerReviewClient -> PeerReviewServer: FitRes(REVIEW=True)
    PeerReviewServer -> PeerReviewStrategy: aggregate_review()
    PeerReviewStrategy -> PeerReviewServer: aggregated_result
    PeerReviewServer -> PeerReviewStrategy: stop_review(aggregated_result)
    PeerReviewStrategy -> PeerReviewServer: stop_flag
end
PeerReviewServer -> PeerReviewStrategy: aggregate_after_review(aggregated_result)
PeerReviewStrategy -> PeerReviewServer: parameters_aggregated
@enduml